# Generated by Django 4.2 on 2023-04-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WrokerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phn_num', models.CharField(blank=True, max_length=13, null=True)),
                ('medical_history', models.TextField(blank=True, max_length=2000, null=True)),
                ('safety_breach', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
