# Generated by Django 4.2 on 2023-04-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WrokerDetails',
            new_name='WorkerDetails',
        ),
    ]
